### PR TITLE
Limit hash characters to 8 for nicer file names

### PR DESCRIPTION
**Pull request by maoberlehner**
The probability of a collision when using the first 8 characters is 1 in
64.000 which should be good enough for this use case.

See: https://stackoverflow.com/a/21805494

### CODE REVIEW

**Comment by maoberlehner** [comment]
What do you think about this change? I think the filenames are a little bit long when using the full hash :P

EDIT: Thinking about it further, this might be better done in the config.

```js
reqHash: (Request) => hash(`${Request.method}${Request.url}${JSON.stringify(Request.headers)}${Request.body}`).substring(0, 8),
```

🤔

**Comment by maoberlehner** [comment]
Oh, I've seen this doesn't work correctly yet – but let me know what you think about this change first, before I investigate further, thx.

**Comment by jaylinski** [comment]
Your reqHash code should work, but I didn't properly implement the hash-retrieval function.

This will work (because the hash is longer than 9 chars) :sweat_smile: 

```js
reqHash: (Request) => hash(`${Request.method}${Request.url}${JSON.stringify(Request.headers)}${Request.body}`).substring(0, 10),
```

See https://github.com/jaylinski/remok/blob/v0.1.2/src/MockFile.js#L34 and https://github.com/jaylinski/remok/blob/v0.1.2/src/Repository.js#L134.   
This is done in order to detect the `@override` key properly. I should probably just try to extract the hash by getting the chars between the first two dots in the filename... :thinking: 

I'll try to fix this the next week. (I'm also open for pull requests :octocat: )

**Comment by jaylinski** [comment]
I released version 0.1.3 with a bugfix. :bug: 

I'll probably simplify the default `reqHash` and `resHash` functions before releasing v1.0.
Right now I'll keep it as it is until I decided/figured out how the hash should look like (in terms of length and source).

**Pull request closed without merging**
